Missing alias for Hash#mash (only had one for mash!)
Fixes test failure:

    undefined method `mash' for {:a=>1, :b=>{:c=>3}}:Hash
Did you mean?  mash!
    lib/core/facets/hash/recursively.rb:28
    26       yld = yld    || lambda{ |k,v| [k,v] }  # ? to_enum
    27       rec = @block || yld #lambda{ |k,v| [k,v] }
 => 28       @enum.__send__(op) do |k,v|
    29         case v
    30         when String # b/c of 1.8
    lib/core/facets/hash/recursively.rb:28
    test/core/hash/test_recursively.rb:45